version: '3.1'

services: 

  api:
    container_name: trydev_api
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/home/trydev_api
      - /home/trydev_api/node_modules

  database: 
    image: postgres
    container_name: trydev_db
    environment:
      POSTGRES_DB: "trydev"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor123"
    ports:
       - "5432:5432"
