version: '3.1'

services: 

  api:
    container_name: trydev_api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - .:/home/trydev_api
    depends_on: 
      - database

  database: 
    image: postgres
    container_name: trydev_db
    environment:
      POSTGRES_DB: "trydev"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor123"
    ports:
       - "5432:5432"
  queue:
    build: .
    volumes:
      - .:/home/trydev_api
    depends_on:
      - database
      - redis
    container_name: queue
    command: yarn dev:queue
  redis:
    image: redis
    ports:
      - "6379:6379"
  adminer:
   image: adminer
   restart: always
   ports:
    - 8080:8080

  